"""add thumb_url for posts

Revision ID: 72709a1aee75
Revises: 3f8cb2f016ef
Create Date: 2019-12-01 15:05:03.638467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72709a1aee75'
down_revision = '3f8cb2f016ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumb_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumb_url')
    # ### end Alembic commands ###
